language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

services:
  - docker

before_install:
  - sed "s/%%PHP_VERSION%%/$(phpenv version-name)/g" Dockerfile.tpl > Dockerfile
  - docker-compose up -d
  - docker ps -a
  - composer update -n

script:
  - ./vendor/bin/phpcs -v --standard=PSR2 src tests/CrowdStar
  - ./vendor/bin/phpunit
