language: php

php:
  - 7.2
  - 7.1
  - 7.0

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps -a

# script:
#   - ./vendor/bin/phpcs -v --standard=PSR2 src tests/CrowdStar
#   - ./vendor/bin/phpunit --exclude-group dockerized
