services:
    web:
        image: nginx:mainline
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        links:
            - php
    php:
        build:
            args:
                PHP_VERSION: ${PHP_VERSION:-8.5}
        volumes:
            - .:/var/www/html
