name: Static Analysis

on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
          coverage: none

      - name: Install PHPStan
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: COMPOSER_NO_AUDIT=1 composer require phpstan/phpstan=~2.0 -n -q --no-progress

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse --no-progress --memory-limit 2G
