name: Syntax Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        php: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Syntax Checks
        run: |
          if [ ${{ matrix.php }} == '7.0' ] ; then
            docker run --rm -v "$(pwd)/src:/data" -i cytopia/phplint:${{ matrix.php }}
          else
            docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php${{ matrix.php }} phplint src
          fi
